### ISSUE TITLE
Your project in the ecosystem-ci

### ISSUE THREAD

**Issue by manniL** [antoinezanardi/werewolves-assistant-web-next#303]
Hey Antoine 👋🏻

As the werewolves-assistant app has well-crafted and broad tests, it might be a good candidate to be added to the Nuxt [ecosystem-ci](https://github.com/nuxt/ecosystem-ci), which could help catching bugs or issues with future Nuxt versions 👀

What do you think?

**Comment by antoinezanardi** [comment]
Hi Alexander !

I wanted to express my gratitude for your interest in my project. It means a lot to me to see it considered as a potential candidate for the Nuxt Ecosystem CI.

You can count me in. How can I contribute ? Let me know what I can do to help move this forward.

**Comment by manniL** [comment]
Awesome! 🙌🏻

Feel free to contribute a test to the repo. An example of an application (elk in this case) [can be found here](https://github.com/nuxt/ecosystem-ci/blob/main/tests/elk.ts). Let me know if you have any questions with regards to how to set it up ☺️

**Comment by antoinezanardi** [comment]
**✅ Resolve reason :** Done with [PR](https://github.com/nuxt/ecosystem-ci/pull/8)
